--- #YAML:1.0
name:               WebService-MoviePosterDB
version:            0.16
abstract:           OO Perl interface to the movie poster database MoviePosterDB.
author:
    - Christopher Key <cjk32@cam.ac.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:     0
    Class::Accessor:      0
    Digest::MD5:          0
    File::Spec::Functions:  0
    JSON:                 0
    LWP::UserAgent:       0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
